# Generated by Django 5.2.16 on 2026-07-11 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('scale', '扩缩容'), ('rollback', '回滚'), ('delete', '删除'), ('apply', '应用YAML'), ('create_user', '创建用户'), ('toggle_active', '启用/禁用用户'), ('reset_password', '重置密码'), ('change_password', '修改密码')], max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_name', models.CharField(blank=True, default='', max_length=255)),
                ('namespace', models.CharField(blank=True, default='', max_length=100)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('success', '成功'), ('fail', '失败')], max_length=20)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='auth_app.user')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
