apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-console-config
  namespace: prd
data:
  DJANGO_DEBUG: "False"
  MYSQL_HOST: "mysql.database.svc"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "appdb"
  REDIS_HOST: "redis.database.svc"
  REDIS_PORT: "6379"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin"
  BUILDER_SERVICE_URL: "http://192.168.1.24:9008"
  ELASTICSEARCH_URL: "http://elasticsearch.prd.svc:9200"
  PROMETHEUS_URL: "http://prometheus.prd.svc:9090"
