# Generated by Django 5.2.16 on 2026-07-12 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProject',
            fields=[
                ('app_name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='应用名称')),
                ('app_type', models.CharField(choices=[('django', 'Django'), ('vue', 'Vue')], max_length=16, verbose_name='应用类型')),
                ('local_path', models.CharField(blank=True, default='', max_length=480, verbose_name='本地代码地址')),
                ('domain', models.CharField(max_length=256, verbose_name='访问域名')),
                ('port', models.IntegerField(default=8000, verbose_name='容器端口（Django=8000, Vue=80）')),
                ('namespace', models.CharField(default='prd', max_length=64, verbose_name='K8s Namespace')),
                ('replicas', models.IntegerField(default=1, verbose_name='Pod 副本数')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_projects', to='clusters.cluster', verbose_name='目标集群')),
            ],
            options={
                'verbose_name': '部署项目',
                'verbose_name_plural': '部署项目',
                'db_table': 'app_project',
            },
        ),
        migrations.CreateModel(
            name='DeployHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, verbose_name='部署 tag')),
                ('status', models.CharField(choices=[('building', '构建中'), ('deploying', '部署中'), ('success', '成功'), ('failed', '失败')], default='building', max_length=16, verbose_name='状态')),
                ('operator', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人')),
                ('message', models.TextField(blank=True, default='', verbose_name='结果信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='部署时间')),
                ('project', models.ForeignKey(db_column='app_name', on_delete=django.db.models.deletion.CASCADE, related_name='deploy_histories', to='deploy.appproject', verbose_name='应用')),
            ],
            options={
                'verbose_name': '部署历史',
                'verbose_name_plural': '部署历史',
                'db_table': 'deploy_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
