apiVersion: v1
kind: Secret
metadata:
  name: k8s-console-secret
  namespace: prd
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "k8s-console-prod-secret-key-change-in-production"
  MYSQL_USER: "appuser"
  MYSQL_PASSWORD: "UserPass2024!"
  REDIS_PASSWORD: "RedisPass2024!"
